### ISSUE TITLE
Documents won't open at all.

### ISSUE THREAD

**Issue by phoenixdataforensics** [muk-it/muk_dms#116]
I just installed Documents and its various file viewers, and it gives this error message when I try to open the documents app.

Error:
Uncaught TypeError: Cannot read property 'find' of undefined

http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:3677
Traceback:
TypeError: Cannot read property 'find' of undefined
    at Class.$ (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:3677:17)
    at Class.destroy (http://phoenixdataforensics.com/web/content/1233-985be9c/web.assets_backend.js:3839:1319)
    at Class.prototype.<computed> [as destroy] (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:3538:488)
    at http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:21:383
    at Function._.map._.collect (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:13:270)
    at Function._.invoke (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:21:294)
    at Class.destroy (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:3673:75)
    at http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:21:383
    at Function._.map._.collect (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:13:270)
    at Function._.invoke (http://phoenixdataforensics.com/web/content/806-10677d2/web.assets_common.js:21:294)

**Comment by keshrath** [comment]
Are you using Odoo 11.0 or 12.?

**Comment by phoenixdataforensics** [comment]
I'm using Odoo 12.

**Comment by phoenixdataforensics** [comment]
Any help?

**Comment by keshrath** [comment]
The error you posted only show the trance in minified js files. You need to reproduce it in debug mode with assets, so I can see wich line of code throws the error.

**Comment by undigo** [comment]
Odoo V11 community version
only error on doc and docx viewer (black screen during ~30 seconds) then this error:
`PDF.js v1.7.225 (identifiant de compilation : 17d135f)
Message : Unexpected server response (502) while retrieving PDF "https://PRIVATE.com/web/preview/msoffice?url=%2Fweb%2Fcontent%3Fmodel%3Dmuk_dms.file%26filename%3Dmodele_lettre_dintention_def_27.12.2018_en_final.docx%26filename_field%3Dname%26field%3Dcontent%26id%3D5%26download%3Dtrue".`


on debug mode browser  Chrome I see:

`web.assets_common.js.pagespeed.jm.QD_P-g60LJ.js:740 Server application error {"code":200,"message":"Odoo Server Error","data":{"name":"builtins.Exception","debug":"Traceback (most recent call last):\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 651, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 693, in dispatch\n    result = self._call_function(**self.params)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 937, in __call__\n    return self.method(*args, **kw)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20190318-py3.7.egg/odoo/addons/bus/controllers/main.py\", line 39, in poll\n    raise Exception(\"bus.Bus only string channels are allowed.\")\nException: bus.Bus only string channels are allowed.\n","message":"bus.Bus only string channels are allowed.","arguments":["bus.Bus only string channels are allowed."],"exception_type":"internal_error"}}
(anonymous) @ web.assets_common.js.pagespeed.jm.QD_P-g60LJ.js:740
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
pdf.worker.js:50046 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
supportsMozChunkedClosure @ pdf.worker.js:50046`

also on pdf.worker.js:50046 code : 
```
var supportsMozChunked = function supportsMozChunkedClosure() {
    try {
     var x = new XMLHttpRequest();
     x.open('GET', 'https://example.com');
     x.responseType = 'moz-chunked-arraybuffer';
     return x.responseType === 'moz-chunked-arraybuffer';
    } catch (e) {
     return false;
    }
```
is it normal that x.open is https://example.com ? 

enough for you @keshrath  to analyse this issue?
best
