### ISSUE TITLE
MUK DMS Error

### ISSUE THREAD

**Issue by itlabsrl-cyber** [muk-it/muk_dms#126]
Hello I have a fresh odoo 11 installation

when i click on menu Documents i have this error

Uncaught ReferenceError: params is not defined

http://ierp.itlabsrl.it/web/content/332-781b52b/web.assets_backend.js:2956
Traceback:
ReferenceError: params is not defined
    at Class.init (http://ierp.itlabsrl.it/web/content/332-781b52b/web.assets_backend.js:2956:124)
    at Class.init (http://ierp.itlabsrl.it/web/content/332-781b52b/web.assets_backend.js:2963:1045)
    at Class.prototype.<computed> [as init] (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:3816:488)
    at new Class (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:3817:65)
    at Object.widget (http://ierp.itlabsrl.it/web/content/332-781b52b/web.assets_backend.js:454:57)
    at Object.<anonymous> (http://ierp.itlabsrl.it/web/content/332-781b52b/web.assets_backend.js:449:219)
    at Object.<anonymous> (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:802:681)
    at fire (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:796:299)
    at Object.add [as done] (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:797:467)
    at Array.<anonymous> (http://ierp.itlabsrl.it/web/content/331-6dee34f/web.assets_common.js:802:649)

how i can solved?

**Comment by keshrath** [comment]
Please reproduce this error while in debug mode with assets otherwise the log can't be debugged.

**Comment by osboer** [comment]
Hello I had the same problem

 odoo 11

Uncaught ReferenceError: params is not defined
http://127.0.0.1:8069/web/content/749-d79a07e/web.assets_backend.js:3075
Traceback:
ReferenceError: params is not defined
    at Class.init (http://127.0.0.1:8069/web/content/749-d79a07e/web.assets_backend.js:3075:124)
    at Class.init (http://127.0.0.1:8069/web/content/749-d79a07e/web.assets_backend.js:3082:1045)
    at Class.prototype.<computed> [as init] (http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:3816:488)
    at new Class (http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:3817:65)
    at Object.widget (http://127.0.0.1:8069/web/content/749-d79a07e/web.assets_backend.js:454:57)
    at http://127.0.0.1:8069/web/content/749-d79a07e/web.assets_backend.js:449:219
    at http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:802:681
    at fire (http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:796:299)
    at Object.add [as done] (http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:797:467)
    at Array.<anonymous> (http://127.0.0.1:8069/web/content/748-7bb0a86/web.assets_common.js:802:649)

**Comment by jcchoquet** [comment]
I have the same problem after update module on Odoo V11. 
My Customer is blocked...

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/596c4a31b1445a66f8253142c4ac41f74b9758c4

**Comment by jcchoquet** [comment]
Thanks for the correction!

**Comment by habihabib** [comment]
Hello,

I have the same error. Could you please tell me how to fix it ?

Thanks

**Comment by keshrath** [comment]
@habihabib are you using the newest version? This should be fixed. You might have to download DMS from Github.

**Comment by habihabib** [comment]
Hello

Ok thank a lot

Best regards

Hicham ABI-HABIB
Consultant (HCM-CH)
t + 41 58 30 76807
hicham.abi-habib@isobar.com

Isobar  |  35 route des Jeunes  |  1227 Geneva  |  Switzerland
isobar.ch<http://isobar.com/ch/en> | facebook <https://www.facebook.com/isobarswitzerland/> |  linkedIn  <https://www.linkedin.com/company/isobar-switzerland> |  twitter<https://twitter.com/IsobarCH>

-------
The information in this e-mail, and those ensuing, is confidential and may be legally privileged. It is intended solely for the addressee.
If you are not the intended recipient, please destroy this message and notify us immediately.
