### ISSUE TITLE
[12.0] muk_dms : Error by using action_dms_files_all_directory

### ISSUE THREAD

**Issue by yweng8111** [muk-it/muk_dms#143]
By using of action_dms_files_all_directory I will get following Error. 
That error is in function search_panel_select_range(). It try to search the "mus_dms.directory" by using the "search_domain" of "mus_dms.file".

Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/lib/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/lib/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  **File "/opt/odoo/lib/addons/muk-dms/muk_dms/models/file.py", line 272, in search_panel_select_range**
    domain, ['display_name', 'parent_directory']
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4837, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 1671, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4358, in _search
    query = self._where_calc(args)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4150, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/lib/odoo/odoo/osv/expression.py", line 673, in __init__
    self.parse()
  File "/opt/odoo/lib/odoo/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'directory' in leaf "<osv.ExtendedLeaf: ('directory', 'child_of', 1) on muk_dms_directory (ctx: )>"

**Comment by keshrath** [comment]
What did you click do get this error? So I can reproduce it.

**Comment by yweng8111** [comment]
You can reproduce it by following steps:
- Click Main Menu "Documents"
- Click Top Menu "Directories"
- Click One of the Directories in Kanban View
- Click Smartbutton "Files"

**Comment by yweng8111** [comment]
It works fine for me locally, if I delete this line
https://github.com/muk-it/muk_dms/blob/346b2d742696343ee025083604ee6fcb2050a65b/muk_dms/models/file.py#L266

**Comment by marylla** [comment]
@keshrath Could you reproduce and in best case already solve this issue?

**Comment by myat90thu** [comment]
https://user-images.githubusercontent.com/35619526/141680256-b70611dd-6c03-49a3-a3e5-4b44f9b8c1e2.mp4

Hi
I purchased from odoo store muk dms bundle and I face this issue. Please see my video for your reference and I also open a ticket in odoo store.

https://user-images.githubusercontent.com/35619526/141680201-fc7ecb77-ba77-4b31-b991-7a5d0a18d095.mp4
![Screenshot 2021-11-14 18:35:49](https://user-images.githubusercontent.com/35619526/141680322-ae5ed6bb-9313-4ec6-aca8-66a20843d8e9.png)
