### ISSUE TITLE
[12.0] muk_dms: Error when clicking on files from a directory

### ISSUE THREAD

**Issue by LeGueux** [muk-it/muk_dms#150]
On a directory form view when i click on the button "Files", i have an error
![image](https://user-images.githubusercontent.com/25929171/98133613-1501ef80-1ebe-11eb-952e-a2e68d38cc64.png)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\ASR\Git\odooGitHub\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "d:\asr\git\odoogithub\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\asr\git\odoogithub\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "d:\asr\git\odoo12_oca_addons\muk_dms\models\file.py", line 272, in search_panel_select_range
    domain, ['display_name', 'parent_directory']
  File "D:\ASR\Git\odooGitHub\odoo\odoo\models.py", line 4578, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\models.py", line 1561, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\models.py", line 4110, in _search
    query = self._where_calc(args)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\models.py", line 3902, in _where_calc
    e = expression.expression(domain, self)
  File "D:\ASR\Git\odooGitHub\odoo\odoo\osv\expression.py", line 672, in __init__
    self.parse()
  File "D:\ASR\Git\odooGitHub\odoo\odoo\osv\expression.py", line 853, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'directory' in leaf "<osv.ExtendedLeaf: ('directory', 'child_of', 1) on muk_dms_directory (ctx: )>"

**Comment by NilmarShereef** [comment]
https://github.com/muk-it/muk_dms/blob/960676159a55e46715a2caeea8e5da560f40e363/muk_dms/models/file.py#L266


Line 266 in file.py

` kwargs.get('search_domain', []), `

Commenting this line will solve the mentioned issue.
Thank You

**Comment by LeGueux** [comment]
Yes it solved this issue.

Thank you.
