### ISSUE TITLE
[11.0] Error when updating muk_dms

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#27]
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 1011, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Das Feld `top_directories` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_settings.form`
[view_id: 1023, xml_id: muk_dms.view_dms_settings_form, model: muk_dms.settings, parent_id: k. A.]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1428, in _update
    record.write(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3016, in write
    self._fields[key].determine_inverse(self)
  File "/usr/local/odoo_11/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nDas Feld `top_directories` existiert nicht\n\nFehler Kontext:\nAnsicht `muk_dms_settings.form`\n[view_id: 1023, xml_id: muk_dms.view_dms_settings_form, model: muk_dms.settings, parent_id: k. A.]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/odoo_11/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/odoo_11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-45>", line 2, in button_immediate_upgrade
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/odoo_11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1428, in _update
    record.write(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3016, in write
    self._fields[key].determine_inverse(self)
  File "/usr/local/odoo_11/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Das Feld `top_directories` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_settings.form`
[view_id: 1023, xml_id: muk_dms.view_dms_settings_form, model: muk_dms.settings, parent_id: k. A.]
None" while parsing /home/odoo/.local/share/Odoo/addons/11.0/muk_dms/views/dms_settings_view.xml:36, near
<record id="view_dms_settings_form" model="ir.ui.view">
	<field name="name">muk_dms_settings.form</field>
	<field name="model">muk_dms.settings</field>
	<field name="arch" type="xml">
		<form string="Document Setting">
			<sheet>
				<label for="name" class="oe_edit_only"/>
				<h1>
					<field name="name"/>
				</h1>
				<group string="Save Settings">
					<group>
						<field name="save_type"/>
					</group>
				</group>
				<group string="Data Settings">
					<group>
						<field name="index_files"/>
						<field name="system_locks"/>
					</group>
					<group>
						<field name="show_tree"/>
					</group>
				</group>
				<notebook>
					<page string="Top Directories">
						<field name="top_directories">
							<tree string="Directories">
								<field name="name"/>
								<field name="size" widget="dms_size"/>
								<field name="count_directories"/>
								<field name="count_files"/>
							</tree>
						</field>
					</page>
					<page string="Top Files">
						<field name="top_files">
							<tree string="Files">
								<field name="name"/>
								<field name="size" widget="dms_size"/>
								<field name="path" widget="dms_path"/>
								<field name="write_date" readonly="1"/>
							</tree>
						</field>
					</page>
					<page string="All Directories">
						<field name="settings_directories">
							<tree string="Directories">
								<field name="name"/>
								<field name="size" widget="dms_size"/>
								<field name="path" widget="dms_path"/>
							</tree>
						</field>
					</page>
					<page string="All Files">
						<field name="settings_files">
							<tree string="Files">
								<field name="name"/>
								<field name="size" widget="dms_size"/>
								<field name="path" widget="dms_path"/>
								<field name="write_date" readonly="1"/>
							</tree>
						</field>
					</page>
					<page string="Root Directories" groups="muk_dms.group_dms_admin">
						<field name="root_directories">
							<tree string="Root Directories">
								<field name="name"/>
								<field name="size" widget="dms_size"/>
								<field name="count_directories"/>
								<field name="count_files"/>
							</tree>
						</field>
					</page>
					<page string="Meta Information" groups="muk_dms.group_dms_admin,base.group_no_one">
						<group>
							<field name="id"/>
						</group>
						<group>
							<group>
								<field name="create_date" readonly="1"/>
								<field name="create_uid" readonly="1"/>
							</group>
							<group>
								<field name="write_date" readonly="1"/>
								<field name="write_uid" readonly="1"/>
							</group>
						</group>
					</page>
				</notebook>
			</sheet>
		</form>
	</field>
</record>
```

**Comment by keshrath** [comment]
If the migration didn't run automatically run the SQL file in your DB manually.
