### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by rafasoyyo** [muk-it/muk_dms#37]
I get this error after install [MuK Documents](https://www.odoo.com/apps/modules/11.0/muk_dms/)
```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 782, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 829, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo muk_web_client_refresh: no se pudo procesar el archivo muk_web_client_refresh/security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'model_muk_web_client_refresh_rule' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_web_client_refresh_rule' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
```

Help please!

**Comment by keshrath** [comment]
The problem seems to be with muk_web_client_refresh. Try to update the module and check if the model muk_web_client_refresh_rule is available in your system.

**Comment by rafasoyyo** [comment]
I am having more issues with your modules but I am not a python expert so I am going to try to fix them by myself before ask.
Thanks for your quick response

**Comment by keshrath** [comment]
Hi, if you need more help just ask :) and in case you find a bug feedback is allways welcome^^
