### ISSUE TITLE
ERROR to INTALL MUK_DMS

### ISSUE THREAD

**Issue by Pereiral01** [muk-it/muk_dms#39]
Hello, I just install a new ODOO 11 (UBUNTU 16 CLOUD SERVER).

Installed basis Odoo app (CRM, LEAVES, CONTACTS,...) and download MUK_DMS, add it to ADDONS.

Then by COMANDS:
Service odoo-server stop
service postgresql restart
service odoo-server start

 and go to ODDO APPs > UPLOAD new APP> Choose MUK_DMS >INSTALL and this error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 782, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 829, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo muk_dms: no se pudo procesar el archivo muk_dms/security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_settings' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_directory' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_file' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_data_database' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_settings' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_data_database' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'model_muk_dms_lock' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)

Could you help me, please?
Many thanks

**Comment by munruf** [comment]
Hi. Just chrk your odoo user permission on the addons folder

вт, 10 апр. 2018 г., 20:38 Pereiral01 <notifications@github.com>:

**Comment by Pereiral01** [comment]
Many thanks ... I restarted server machines and WORK for me!

Thanks for your fasta reply!

**Comment by Pereiral01** [comment]
Hello Keshrath, open it again...
Before restart the server, i go to App Panel and choose DOCUMENTS.... but it didn’t open and show this error:

“Could not find client action: “muk_dms_views.documents”

I view there is a new version (35) > download> upload to addons> and restart server: Odoo broken (Internal error)

So, copy again to ADDONS the last version (34), restart server and now: BLANK PAGE...

Any help please?
Many thanks again

**Comment by munruf** [comment]
1. Tray to install module again.
If it will not help.
Uninstall and reinstall module.
If not solve solution folow previouse  soggestion swithch back to last
working version

ср, 11 апр. 2018 г., 3:00 Pereiral01 <notifications@github.com>:

**Comment by keshrath** [comment]
Hello .)
If it still doesn't work, please send me some log information. 
Browserlog with debug=assets and the Odoo log would be great.
Are you using version 10 or 11?

**Comment by Pereiral01** [comment]
Hello Keshrath,
I´m a rookie ... How I can show Browserlog with debug=assets, please?
Many thanks

**Comment by keshrath** [comment]
You need to write it into the URL for example: /web?debug=assets

**Comment by keshrath** [comment]
Have you restarted the server after the module installation?

**Comment by Pereiral01** [comment]
Hello, yes I restarted it. I'm working with ODOO 11 (UBUNTU 16).

When I use DEBUG with ASSETS, I saw this:

![abr-11-2018 17-53-30](https://user-images.githubusercontent.com/38085740/38628797-886c5608-3db2-11e8-9298-f18b8f91c2b1.gif)



![abr-11-2018 13-17-59](https://user-images.githubusercontent.com/38085740/38627886-4b6704a8-3db0-11e8-9bd0-7a7415390512.gif)

**Comment by keshrath** [comment]
Unfortunately I can't see anything on your pictures, because the resolution is too low.

**Comment by Pereiral01** [comment]
Finally, It works. I did this:

- UNINSTALLL MUK_DMS
- Upload again MUK_DMS
- Before to re-install MUK_DMS, I UPDATE MUK_UTILS & MUK_WEB
- INSTALL MUK_DMS
- RESTART SERVER

It works ..... but now I have. little Problem ....

When I logged with a **USER account** and try to upload a File it give me a ERROR. It says:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 5027, in onchange
    record = self.new(values)
  File "/odoo/odoo-server/odoo/models.py", line 4553, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/odoo/odoo-server/odoo/tools/func.py", line 23, in __get__
    value = self.fget(obj)
  File "/odoo/odoo-server/odoo/models.py", line 4747, in _cache
    return RecordCache(self)
  File "/odoo/odoo-server/odoo/models.py", line 5106, in __init__
    assert len(record) == 1, "Unexpected RecordCache(%s)" % record
AssertionError: Unexpected RecordCache(muk_dms.file())

**Comment by keshrath** [comment]
Do you have installed muk_dms_access as well? Which rights does this user have?

**Comment by Pereiral01** [comment]
Keshrath ... solved.

I´m a dummy ... the problem was the user hasn't rights for any directory. ... very simple, but I forget it! . Apologies.

Could you help in the last question, please?: Does this module create a NEW DATABASE (only for files) or save the FILES in  Odoo´s DATABASE?
How can BACKUP only Document´s DATABASE?

Many thanks!

**Comment by Pereiral01** [comment]
and Could I UPLOAD massive files in one time?
Many thanks

**Comment by keshrath** [comment]
So where the files will be saved to will depend on the setting in the settings. In the core module muk_dms the data is stored in the database and can be backed up directly with Odoo. You can also have a look at the modules muk_dms_file (Filestore) and muk_dms_lobject (DB LObjects) for more possibilities.

**Comment by keshrath** [comment]
In the Document View you can load files and entire folders directly into the system using drag and drop. The amount of data is limited by Odoo in amount and time of the request.

**Comment by Pereiral01** [comment]
Hi Mathias,
Could you answer me one question, please? I´m very happy with MUK DOCUMENTS.
Are there any field, o module, to include a COMMENT field for each file? the idea is writte soame word about specs of each file.
Many thanks
Raul

**Comment by keshrath** [comment]
Hello, Raul,
thank you for your positive feedback. We have a module which will extend the DMS by a better indexing a search and in this course possibly also a comment field in planning. However, at the moment we are quite involved in other projects, so it is very difficult for me to give you a schedule. However, if you have any special requirements I can offer you to contact sale@mukit.at and we can make you an offer for your requirements.
Regards
Mathias
