### ISSUE TITLE
muk_dms_access can not be installed

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#51]
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 1048, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Das Feld `inherit_groups` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_directory.form`
[view_id: 1792, xml_id: k. A., model: muk_dms.directory, parent_id: 1766]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nDas Feld `inherit_groups` existiert nicht\n\nFehler Kontext:\nAnsicht `muk_dms_directory.form`\n[view_id: 1792, xml_id: k. A., model: muk_dms.directory, parent_id: 1766]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/odoo_11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/odoo_11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/odoo_11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Das Feld `inherit_groups` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_directory.form`
[view_id: 1792, xml_id: k. A., model: muk_dms.directory, parent_id: 1766]
None" while parsing /home/odoo/.local/share/Odoo/addons/11.0/muk_dms_access/views/dms_directory_view.xml:22, near
<record id="view_dms_directory_form" model="ir.ui.view">
	<field name="name">muk_dms_directory.form</field>
	<field name="model">muk_dms.directory</field>
	<field name="inherit_id" ref="muk_dms.view_dms_directory_form"/>
	<field name="arch" type="xml">
		<data><xpath expr="//field[@name='is_root_directory']" position="after">
			<field name="inherit_groups" groups="muk_dms.group_dms_manager"/>
		</xpath>
		<xpath expr="//page[last()]" position="after">
			<page string="Groups" groups="muk_dms.group_dms_manager">
				<field name="groups">
					<tree string="Groups">
						<field name="name"/>
						<field name="perm_read"/>
						<field name="perm_create"/>
						<field name="perm_write"/>
						<field name="perm_unlink"/>
					</tree>
				</field>
			</page>
			<page string="Complete Groups" groups="muk_dms.group_dms_manager">
				<field name="complete_groups">
					<tree string="Complete Groups">
						<field name="name"/>
						<field name="perm_read"/>
						<field name="perm_create"/>
						<field name="perm_write"/>
						<field name="perm_unlink"/>
					</tree>
				</field>
			</page>
		</xpath>
	</data></field>
</record>
```

**Comment by keshrath** [comment]
Also ich habe es bis dato nicht geschafft dieses Fehler zu reproduzieren. Auch auf unserem Demo Server sind die neuen Versionen installiert. Hast du bereits gecheckt, ob du die neuersten Versionen aller Dependencies hast und anschließende den Server restartet vor dem Update.

**Comment by satriani-vai** [comment]
Ich habe extra alles aus dem github geholt.
Anschließend den Server neugestartet, doch leider mit gleichem Ergebnis.

**Comment by moblesmarti** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1033, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1042, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
    raise ValueError(message)
ValueError: El campo inherit_groups no existe

Contexto del error:
Vista muk_dms_directory.form
[view_id: 1881, xml_id: muk_dms_access.view_dms_directory_form, model: muk_dms.directory, parent_id: 1871]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3094, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3076, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3242, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1037, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nEl campo inherit_groups no existe\n\nContexto del error:\nVista `muk_dms_directory.form`\n[view_id: 1881, xml_id: muk_dms_access.view_dms_directory_form, model: muk_dms.directory, parent_id: 1871]', None)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 936, in call
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-49>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3094, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3076, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3242, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1037, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

El campo inherit_groups no existe

Contexto del error:
Vista muk_dms_directory.form
[view_id: 1881, xml_id: muk_dms_access.view_dms_directory_form, model: muk_dms.directory, parent_id: 1871]
None" while parsing /opt/odoo/otros_modulos/muk_dms_access/views/dms_directory_view.xml:22, near
<record id="view_dms_directory_form" model="ir.ui.view">
  <field name="name">muk_dms_directory.form</field>
  <field name="model">muk_dms.directory</field>
  <field name="inherit_id" ref="muk_dms.view_dms_directory_form"/>
  <field name="arch" type="xml">
    <data><xpath expr="//field[@name='is_root_directory']" position="after">
      <field name="inherit_groups" groups="muk_dms.group_dms_manager"/>
    </xpath>
    <xpath expr="//page[last()]" position="after">
      <page string="Groups" groups="muk_dms.group_dms_manager">
        <field name="groups">
          <tree string="Groups">
            <field name="name"/>
            <field name="perm_read"/>
            <field name="perm_create"/>
            <field name="perm_write"/>
            <field name="perm_unlink"/>
          </tree>
        </field>
      </page>
      <page string="Complete Groups" groups="muk_dms.group_dms_manager">
        <field name="complete_groups">
          <tree string="Complete Groups">
            <field name="name"/>
            <field name="perm_read"/>
            <field name="perm_create"/>
            <field name="perm_write"/>
            <field name="perm_unlink"/>
          </tree>
        </field>
      </page>
    </xpath>
  </data></field>
</record>

**Comment by moblesmarti** [comment]
![photo_2018-07-19_10-51-40](https://user-images.githubusercontent.com/12881456/42932123-c509ce92-8b41-11e8-91e7-4b3cd087d4de.jpg)

**Comment by moblesmarti** [comment]
We have a problem, the new versions of the modules to update give us the error described. 
Attached image in previous message.
From the local and remote version we get the same version, but we can not update them.

**Comment by keshrath** [comment]
It could be that the DMS modules are up-to-date but not the dependencies. With the 2.0 update, not only the DMS but also almost all dependencies have changed. Especially the modules MuK Utils and MuK Security. Are you testing the update on a fresh database or on an existing one? With an existing database it can happen that Odoo does not update the tables correctly and then the postgres database has to be changed manually. So you may have to add the field manually.

**Comment by moblesmarti** [comment]
I can not solve this error, has anyone succeeded?
Thank you!

**Comment by keshrath** [comment]
Have your tried to add the field manually?

**Comment by moblesmarti** [comment]
I will continue trying for now I can not solve it. Could another solution be to return to the previous version of the module?
Thank you!

**Comment by Kerrim-** [comment]
Hi,

can someone who has this problem and can share his screen or similar write us an e-mail as we can't reproduce this bug. We would then post the answer.

email: office@mukit.at

Regards,
Kerrim

**Comment by keshrath** [comment]
A problem seems to exist if one or both obsolete modules muk_dms_connector and muk_dms_access_connector are inside the addons folder. These were discarded in the 2.0 rework and are no longer required. However, since these two modules were not adapted to the 2.0 versions this seems to lead to problems if they are still in the addon folder.

Please make sure that these modules have been removed accordingly.

Can anyone confirm that this has solved the error?

**Comment by moblesmarti** [comment]
Effectively, this solves the error...
Thank you!! :))
