### ISSUE TITLE
muk_thumbnails verursacht einen Fehler

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#53]
```
2018-08-01 08:51:42,707 55560 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/odoo_11/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/local/odoo_11/odoo/service/wsgi_server.py", line 164, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/odoo_11/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/local/odoo_11/odoo/http.py", line 1317, in __call__
    self.load_addons()
  File "/usr/local/odoo_11/odoo/http.py", line 1349, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
    
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
    
  File "/usr/local/odoo_11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 20, in <module>
    
  File "/usr/home/odoo/.local/share/Odoo/addons/11.0/muk_dms_thumbnails/models/__init__.py", line 20, in <module>
    from . import dms_file
  File "/usr/home/odoo/.local/share/Odoo/addons/11.0/muk_dms_thumbnails/models/dms_file.py", line 33, in <module>
    from odoo.addons.muk_thumbnails.tools import thumbnail
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
    
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
    
  File "/usr/local/odoo_11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 20, in <module>
    
  File "/usr/home/odoo/.local/share/Odoo/addons/11.0/muk_thumbnails/service/__init__.py", line 20, in <module>
    from . import thumbnail
  File "/usr/home/odoo/.local/share/Odoo/addons/11.0/muk_thumbnails/service/thumbnail.py", line 56, in <module>
    from moviepy.editor import VideoFileClip
  File "/usr/local/lib/python3.6/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/usr/local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 69, in download
    raise RuntimeError("FFMPEG exe isn't available for platform %s" % plat)
RuntimeError: FFMPEG exe isn't available for platform None
```

**Comment by keshrath** [comment]
Sieht so aus als wäre FFMPEG nicht installiert.
Du brauchst:
Unoconv 
FFMPEG 
Ghostscript 
ImageMagick
Siehe: https://github.com/muk-it/muk_base/blob/11.0/muk_thumbnails/doc/index.rst

**Comment by keshrath** [comment]
Closed since no further information has been provided.
