### ISSUE TITLE
muk_dms_access kann nicht installiert werden

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#54]
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 1048, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Das Feld `inherit_groups` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_directory.form`
[view_id: 1413, xml_id: k. A., model: muk_dms.directory, parent_id: 971]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1482, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nDas Feld `inherit_groups` existiert nicht\n\nFehler Kontext:\nAnsicht `muk_dms_directory.form`\n[view_id: 1413, xml_id: k. A., model: muk_dms.directory, parent_id: 971]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/odoo_11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/odoo_11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/odoo_11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1482, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Das Feld `inherit_groups` existiert nicht

Fehler Kontext:
Ansicht `muk_dms_directory.form`
[view_id: 1413, xml_id: k. A., model: muk_dms.directory, parent_id: 971]
None" while parsing /home/odoo/.local/share/Odoo/addons/11.0/muk_dms_access/views/dms_directory_view.xml:22, near
<record id="view_dms_directory_form" model="ir.ui.view">
	<field name="name">muk_dms_directory.form</field>
	<field name="model">muk_dms.directory</field>
	<field name="inherit_id" ref="muk_dms.view_dms_directory_form"/>
	<field name="arch" type="xml">
		<data><xpath expr="//field[@name='is_root_directory']" position="after">
			<field name="inherit_groups" groups="muk_dms.group_dms_manager"/>
		</xpath>
		<xpath expr="//page[last()]" position="after">
			<page string="Groups" groups="muk_dms.group_dms_manager">
				<field name="groups">
					<tree string="Groups">
						<field name="name"/>
						<field name="perm_read"/>
						<field name="perm_create"/>
						<field name="perm_write"/>
						<field name="perm_unlink"/>
					</tree>
				</field>
			</page>
			<page string="Complete Groups" groups="muk_dms.group_dms_manager">
				<field name="complete_groups">
					<tree string="Complete Groups">
						<field name="name"/>
						<field name="perm_read"/>
						<field name="perm_create"/>
						<field name="perm_write"/>
						<field name="perm_unlink"/>
					</tree>
				</field>
			</page>
		</xpath>
	</data></field>
</record>
```

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/issues/51
