### ISSUE TITLE
Problems with database manager after muk_dms installation

### ISSUE THREAD

**Issue by bennals** [muk-it/muk_dms#71]
I've been using the 2.0 version of muk_dms on 11 CE or a few weeks now without any trouble, but I tried to drop a database via web/database/manager just now and received the following error.

2019-02-20 04:27:45,611 20216 ERROR test odoo.http: muk_dms.settings
Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/odoo-server/odoo/service/db.py", line 453, in dispatch
    return g[exp_method_name](*params)
  File "<decorator-gen-293>", line 2, in exp_drop
  File "/home/odoo/odoo-server/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/home/odoo/thirdparty/addons/muk_dms_file/base/service_db.py", line 64, in exp_drop
    settings = env['muk_dms.settings'].search([('save_type', '=', 'file')])
  File "/home/odoo/odoo-server/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/odoo/odoo-server/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'muk_dms.settings'

I also tried to backup a server and got the same results.

Any suggestions as to what I should try?

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/pull/63

**Comment by bennals** [comment]
Thank you, that seems to have fixed the problem.  Also was having trouble with restoring a database which seemed to be related to muk_security but the update three days ago seems to have fixed that, so thanks for that as well.
