### ISSUE TITLE
Cannot Install MUK DMS 12.0.2.5.11

### ISSUE THREAD

**Issue by asolano88** [muk-it/muk_dms#73]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/fields.py", line 975, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo12/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users[1].groups_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 779, in read_combined
    parent_view = root.inherit_id.read_combined(fields=fields)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 784, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 727, in apply_view_inheritance
    sql_inherit = self.get_inheriting_views_arch(source_id, model)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 508, in get_inheriting_views_arch
    user_groups = self.env.user.groups_id
  File "/opt/odoo12/odoo/odoo/fields.py", line 979, in __get__
    self.determine_value(record)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1080, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo12/odoo/odoo/models.py", line 2827, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_users.py", line 1162, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_users.py", line 406, in read
    return super(Users, self).read(fields=fields, load=load)
  File "/opt/odoo12/odoo/odoo/models.py", line 2765, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_users.py", line 364, in _read_from_database
    super(Users, self)._read_from_database(field_names, inherited_field_names)
  File "/opt/odoo12/odoo/odoo/models.py", line 2926, in _read_from_database
    field.read(fetched)
  File "/opt/odoo12/odoo/odoo/fields.py", line 2674, in read
    for record in records:
  File "/opt/odoo12/odoo/odoo/models.py", line 4957, in __iter__
    yield self._browse((id,), self.env, self._prefetch, False)
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1109, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\n_browse() takes from 3 to 4 positional arguments but 5 were given', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1109, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

_browse() takes from 3 to 4 positional arguments but 5 were given
None" while parsing /opt/odoo12/odoo-custom-addons/muk_security/views/access_groups.xml:22, near
<record id="view_security_access_groups_tree" model="ir.ui.view">
	<field name="name">muk_security_access_groups.tree</field>
	<field name="model">muk_security.access_groups</field>
    <field name="mode">primary</field>
    <field name="inherit_id" ref="muk_utils.view_mixins_groups_tree"/>
	<field name="arch" type="xml">
		<xpath expr="//field[@name='name']" position="after">
			<field name="perm_read"/>
			<field name="perm_create"/>
			<field name="perm_write"/>
			<field name="perm_unlink"/>
		</xpath>
	</field>
</record>

**Comment by digitalliuzg** [comment]
OCB V12 install for bug

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: no mixin named mk-flex-container

       Backtrace:
       	stdin:7974
        on line 7974 of stdin
>> 		@include mk-flex-container(column);
   -----------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /muk_web_utils/static/src/scss/variables.scss
    - /muk_web_utils/static/src/scss/switch.scss
    - /muk_web_utils/static/src/scss/dropzone.scss
    - /muk_web_utils/static/src/scss/module.scss
    - /muk_web_utils/static/src/scss/color.scss
    - /muk_web_utils/static/src/scss/image.scss
    - /muk_web_utils/static/src/scss/copy.scss
    - /muk_web_utils/static/src/scss/share.scss
    - /muk_web_utils/static/src/scss/notification.scss
    - /muk_dms/static/src/scss/variables.scss
    - /muk_dms/static/src/scss/directory_kanban.scss
    - /muk_dms/static/src/scss/file_kanban.scss
    - /web_settings_dashboard/static/src/scss/dashboard.scss

**Comment by digitalliuzg** [comment]
OCB v12

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_web/blob/12.0/muk_web_utils/static/src/scss/mixins.scss#L20

**Comment by digitalliuzg** [comment]
Ok ，Solved ,Thank you.

**Comment by LucianoCM75** [comment]
Dear, I can not create directories with "muk_dms" in Odoo 12, presents the following and message:
Error validating a constraint

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document Type: Directory, Operation: read) - (Records: [19], User: 2)
None
