### ISSUE TITLE
MUK Document Attachment

### ISSUE THREAD

**Issue by asolano88** [muk-it/muk_dms#75]
After installing the MUK Document Attachment, got this error when setting up (clicking) the "attachments" button to set the location.

Error:
Uncaught Error: Expected "}", got "(string)"

http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:143
Traceback:
Error: Expected "}", got "(string)"
    at advance (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:143:50)
    at F.symbol.nud (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:132:1)
    at expression (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:141:146)
    at Object.py.parse (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:259:462)
    at Object.py.eval (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:274:296)
    at http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:410:110
    at iterator (http://192.168.0.27:8069/web/content/353-1c0ccbe/web.assets_common.js:14:183)
    at Function.<anonymous> (http://192.168.0.27:8069/web/content/353-1c0ccbe/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (http://192.168.0.27:8069/web/content/353-1c0ccbe/web.assets_common.js:69:526)
    at eval_contexts (http://192.168.0.27:8069/web/content/468-5d285c5/web.assets_backend.js:408:136)

**Comment by keshrath** [comment]
Javascript errors without debug=assets are unfortunately not verifiable

**Comment by asolano88** [comment]
I tried the MUK demo site and it has the same error.

**Comment by keshrath** [comment]
```
Error:
Uncaught Error: Expected "}", got "(string)"

https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:360
Traceback:
Error: Expected "}", got "(string)"
    at advance (https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:360:19)
    at F.symbol.nud (https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:253:9)
    at expression (https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:350:22)
    at Object.py.parse (https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:1320:16)
    at Object.py.eval (https://demo12.mukit.at/web/static/lib/py.js/lib/py.js:1459:16)
    at https://demo12.mukit.at/web/static/src/js/core/py_utils.js:118:28
    at iterator (https://demo12.mukit.at/web/static/lib/underscore/underscore.js:176:16)
    at Function.<anonymous> (https://demo12.mukit.at/web/static/lib/underscore/underscore.js:191:14)
    at _.(anonymous function) [as reduce] (https://demo12.mukit.at/web/static/lib/underscore/underscore.js:1484:34)
    at eval_contexts (https://demo12.mukit.at/web/static/src/js/core/py_utils.js:106:24)
```

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/61607da6865fc46347569d71c2b0f3253f4e8503
