### ISSUE TITLE
Document View v.12 - Create Button

### ISSUE THREAD

**Issue by asolano88** [muk-it/muk_dms#86]
On Clicking "CREATE" Button

The following error will appear:

Error:
Uncaught TypeError: this.controller._createNode is not a function

http://192.168.0.228:8069/web/content/25398-37c058e/web.assets_backend.js:3861
Traceback:
TypeError: this.controller._createNode is not a function
    at Class._create_selected_node (http://192.168.0.228:8069/web/content/25398-37c058e/web.assets_backend.js:3861:859)
    at HTMLButtonElement.dispatch (http://192.168.0.228:8069/web/content/444-01898e3/web.assets_common.js:892:451)
    at HTMLButtonElement.elemData.handle (http://192.168.0.228:8069/web/content/444-01898e3/web.assets_common.js:865:173)

**Comment by keshrath** [comment]
Can you please send the trace while in debug mode with assets

**Comment by asolano88** [comment]
Error:
Uncaught TypeError: this.controller._createNode is not a function

http://192.168.0.228:8069/muk_dms_view/static/src/js/views/main/main.js:247
Traceback:
TypeError: this.controller._createNode is not a function
    at Class._create_selected_node (http://192.168.0.228:8069/muk_dms_view/static/src/js/views/main/main.js:247:23)
    at HTMLButtonElement.dispatch (http://192.168.0.228:8069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLButtonElement.elemData.handle (http://192.168.0.228:8069/web/static/lib/jquery/jquery.js:4309:63)


________________________________

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/e2c2d786cda98eb5d3ca56313051585e28892665
