### ISSUE TITLE
DMS ver 12- using Filter for the Field Tags

### ISSUE THREAD

**Issue by asolano88** [muk-it/muk_dms#89]
At the Files Menu:
Select Filters
Add Custom Filter
Select Field **Tags** condition (contains, not equal to , etc) = "value"

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo-custom-addons/muk_dms/models/file.py", line 301, in search_panel_select_multi_range
    return super(File, self).search_panel_select_multi_range(field_name, **kwargs)
  File "/opt/odoo12/odoo-custom-addons/muk_web_searchpanel/models/base.py", line 132, in search_panel_select_multi_range
    groups = self.read_group(model_domain, [field_name], [field_name])
  File "/opt/odoo12/odoo/odoo/models.py", line 2070, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo12/odoo/odoo/models.py", line 2093, in _read_group_raw
    query = self._where_calc(domain)
  File "/opt/odoo12/odoo/odoo/models.py", line 3879, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo12/odoo/odoo/osv/expression.py", line 672, in __init__
    self.parse()
  File "/opt/odoo12/odoo/odoo/osv/expression.py", line 1023, in parse
    ids2 = [x[0] for x in comodel.name_search(right, domain or [], op2, limit=None)]
  File "/opt/odoo12/odoo/odoo/models.py", line 1643, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/opt/odoo12/odoo/odoo/models.py", line 1656, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/opt/odoo12/odoo/odoo/models.py", line 4083, in _search
    if expression.is_false(self, args):
  File "/opt/odoo12/odoo/odoo/osv/expression.py", line 225, in is_false
    elif token[1] == 'in' and not token[2]:
IndexError: string index out of range

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/pull/103 --> https://github.com/muk-it/muk_dms/commit/cb30e298e35d507b880ddf8847db175ef620c969
