### ISSUE TITLE
[12.0] Client error 

### ISSUE THREAD

**Issue by miguelsilvazup** [muk-it/muk_dms#90]
I have installed muk_dms in Odoo 12.0 and it shows the following erros: 

```

> Erro:
> Uncaught Error: QWeb2: Template 'SearchPanel.Category' not found
> 
> http://34.229.19.40/web/content/378-d072956/web.assets_common.js:3374
> Traceback:
> Error: QWeb2: Template 'SearchPanel.Category' not found
>     at Object.exception (http://34.229.19.40/web/content/378-d072956/web.assets_common.js:3374:7)
>     at Engine._render (http://34.229.19.40/web/content/378-d072956/web.assets_common.js:3419:103)
>     at Engine.render (http://34.229.19.40/web/content/378-d072956/web.assets_common.js:3415:151)
>     at Class._renderCategory (http://34.229.19.40/web/content/434-d6be485/web.assets_backend.js:3298:608)
>     at http://34.229.19.40/web/content/434-d6be485/web.assets_backend.js:3298:477
>     at Array.forEach (<anonymous>)
>     at Class._render (http://34.229.19.40/web/content/434-d6be485/web.assets_backend.js:3298:361)
>     at Object.<anonymous> (http://34.229.19.40/web/content/434-d6be485/web.assets_backend.js:3286:36)
>     at Object.<anonymous> (http://34.229.19.40/web/content/378-d072956/web.assets_common.js:802:681)
>     at fire (http://34.229.19.40/web/content/378-d072956/web.assets_common.js:796:299)

```

**Comment by keshrath** [comment]
Check access rights of Odoo to the addon folder. Restart the server and update the searchpanel app again.

**Comment by miguelsilvazup** [comment]
> Check access rights of Odoo to the addon folder. Restart the server and update the searchpanel app again.

Thx, it looks like working perfectly.
